#! /usr/bin/env python

import sys
from darkflow.cli import cliHandler
import tensorflow as tf
config = tf.ConfigProto(gpu_options=tf.GPUOptions(allow_growth=True))
sess = tf.Session(config=config)
cliHandler(sys.argv)

